default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        additional_dependencies: [black==24.3.0]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        args: ["--load-plugins=pylint_django", "--django-settings-module=Quantum.settings", '--ignore-paths=".*/static/.*,.*/management/commands/.*,.*/frontend/.*,.*/collectedstatic/.*,manage.py"', "--disable=import-error,django-not-available,unused-argument"]
        additional_dependencies: [pylint-django==2.5.5]

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports", "--remove-unused-variables", "--expand-star-imports", "--remove-duplicate-keys", "--ignore-init-module-imports", "--recursive"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ['--write', '--ignore-path', '.gitignore']
        files: (.+\.js$)|(.+\.ts$)|(.+\.vue$)|(.+\.scss$)|(.+\.html$)|(.+\.md$)|(.+\.json$)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: (.+\.js$)|(.+\.ts$)|(.+\.vue$)
        types: ["file"]
  # - repo: local
  #   hooks:
  #     - id: djlint
  #       name: djlint
  #       entry: djlint --quiet --profile django --reformat
  #       language: system
  #       types: [html]
  #       files: (.+\.html$)
  #     - id: vue-type-check
  #       name: vue-type-check
  #       entry: sh -c 'cd frontend && yarn ts'
  #       language: system
  #       files: (.+\.js$)|(.+\.ts$)|(.+\.vue$)
  #       pass_filenames: true
